@startuml
'https://plantuml.com/class-diagram

package figureButtons{

abstract class FigureButton{
    # {final} PaintPane paintPane
    # {final} CanvasState canvasState
    + FigureButton(PaintPane paintPane, CanvasState canvasState)
    + void createAndAddFigure(Point startPoint, Point endPoint)
    + {abstract} Figure createFigure(Point startPoint, Point endPoint)
}
class RectangleButton extends FigureButton{
    + RectangleButton(PaintPane paintPane, CanvasState canvasState)
    + Rectangle createFigure(Point startPoint, Point endPoint)
}
class SquareButton extends RectangleButton{
    + SquareButton(PaintPane paintPane, CanvasState canvasState)
    + Square createFigure(Point startPoint, Point endPoint)
}
class EllipseButton extends FigureButton{
    + EllipseButton(PaintPane paintPane, CanvasState canvasState)
    + Ellipse createFigure(Point startPoint, Point endPoint)
}
class CircleButton extends EllipseButton{
    + CircleButton(PaintPane paintPane, CanvasState canvasState)
    + Circle createFigure(Point startPoint, Point endPoint)
}



}

@enduml